# Generated by Django 3.2.7 on 2021-11-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='description',
            field=models.TextField(default='a real stinker', max_length=250),
        ),
        migrations.AddField(
            model_name='finch',
            name='name',
            field=models.CharField(default='Dorkus', max_length=100),
        ),
        migrations.AddField(
            model_name='finch',
            name='species',
            field=models.CharField(default='House Finch', max_length=100),
        ),
    ]
